# Generated by Django 6.0.6 on 2026-07-03 19:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_totp_enabled_user_totp_enabled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=accounts.models.profile_picture_upload_path),
        ),
    ]
