# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contribution_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='public_badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='public_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='public_location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='public_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
