# Generated by Django 6.0.6 on 2026-07-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_public_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_report_created_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_report_status_changed_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_sighting_created_email',
            field=models.BooleanField(default=True),
        ),
    ]
