# Generated by Django 6.0.6 on 2026-07-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_notification_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish'), ('nl', 'Dutch')], default='en', max_length=8),
        ),
    ]
