# Generated by Codex on 2026-07-06

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostCatReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
                ('age_years', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('coat_color', models.CharField(max_length=120)),
                ('eye_color', models.CharField(blank=True, max_length=80)),
                ('gender', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('FEMALE', 'Female'), ('MALE', 'Male')], default='UNKNOWN', max_length=20)),
                ('collar_description', models.CharField(blank=True, max_length=200)),
                ('has_microchip', models.BooleanField(default=False)),
                ('chip_number', models.CharField(blank=True, max_length=64)),
                ('personality', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('disappeared_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_address', models.CharField(max_length=255)),
                ('last_seen_landmark', models.CharField(blank=True, max_length=180)),
                ('last_seen_lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('last_seen_lng', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reward_note', models.CharField(blank=True, max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=40)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_visibility', models.CharField(choices=[('APP_ONLY', 'Logged-in helpers only'), ('PUBLIC', 'Public'), ('PRIVATE', 'Owner only')], default='APP_ONLY', max_length=20)),
                ('notify_push', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('MISSING', 'Missing'), ('RECENTLY_SEEN', 'Recently seen'), ('FOUND', 'Found'), ('CLOSED', 'Closed')], default='MISSING', max_length=20)),
                ('moderation_status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('HIDDEN', 'Hidden')], default='PENDING', max_length=20)),
                ('moderation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_cat_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddIndex(
            model_name='lostcatreport',
            index=models.Index(fields=['owner', '-updated_at'], name='reports_los_owner_i_71b1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='lostcatreport',
            index=models.Index(fields=['status', '-updated_at'], name='reports_los_status_38529f_idx'),
        ),
        migrations.AddIndex(
            model_name='lostcatreport',
            index=models.Index(fields=['moderation_status', '-updated_at'], name='reports_los_moderat_7092bc_idx'),
        ),
    ]
