# Generated by Django 6.0.6 on 2026-07-06 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostCatReportTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('STATUS_CHANGED', 'Status changed')], max_length=40)),
                ('from_status', models.CharField(blank=True, choices=[('MISSING', 'Missing'), ('RECENTLY_SEEN', 'Recently seen'), ('FOUND', 'Found'), ('CLOSED', 'Closed')], max_length=20)),
                ('to_status', models.CharField(blank=True, choices=[('MISSING', 'Missing'), ('RECENTLY_SEEN', 'Recently seen'), ('FOUND', 'Found'), ('CLOSED', 'Closed')], max_length=20)),
                ('location_summary', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_cat_report_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='reports.lostcatreport')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['report', '-created_at'], name='reports_los_report__1bd76d_idx'), models.Index(fields=['event_type', '-created_at'], name='reports_los_event_t_5e0883_idx')],
            },
        ),
    ]
