# Generated by Django 6.0.6 on 2026-07-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_lostcatreporttimelineevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcatreport',
            name='found_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lostcatreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
