# Generated by Django 6.0.6 on 2026-07-06 19:12

import django.db.models.deletion
import reports.models
import reports.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_lostcatreport_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostCatReportPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=reports.models.lost_cat_report_photo_upload_to, validators=[reports.validators.validate_report_photo_upload])),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.lostcatreport')),
            ],
            options={
                'ordering': ('-is_main', 'created_at'),
                'indexes': [models.Index(fields=['report', 'is_main'], name='reports_los_report__99879a_idx'), models.Index(fields=['report', 'created_at'], name='reports_los_report__d1a45f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('report',), name='unique_main_lost_cat_report_photo')],
            },
        ),
    ]
