# Generated by Django 6.0.6 on 2026-07-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_lostcatreportphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostcatreporttimelineevent',
            name='event_type',
            field=models.CharField(choices=[('STATUS_CHANGED', 'Status changed'), ('SIGHTING_CREATED', 'Sighting created')], max_length=40),
        ),
    ]
