# Generated by Django 6.0.6 on 2026-07-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_lostcatreporttimelineevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostcatreporttimelineevent',
            name='event_type',
            field=models.CharField(choices=[('REPORT_CREATED', 'Report created'), ('STATUS_CHANGED', 'Status changed'), ('SIGHTING_CREATED', 'Sighting created')], max_length=40),
        ),
    ]
