# Generated by Django 6.0.6 on 2026-07-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_lostcatreporttimelineevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostcatreporttimelineevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('REPORT_CREATED', 'Report created'),
                    ('STATUS_CHANGED', 'Status changed'),
                    ('SIGHTING_CREATED', 'Sighting created'),
                    ('SIGHTING_MARKED_USEFUL', 'Sighting marked useful'),
                    ('SIGHTING_MARKED_FALSE', 'Sighting marked false'),
                    ('VOLUNTEER_SEARCH_STARTED', 'Volunteer search started'),
                ],
                max_length=40,
            ),
        ),
    ]
