# Generated by Django 6.0.6 on 2026-07-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_lostcatreporttimelineevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcatreport',
            name='public_summary',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
