# Generated by Django 6.0.6 on 2026-07-07 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0009_alter_lostcatreporttimelineevent_event_type'),
        ('sightings', '0004_volunteersearch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('REPORT_CREATED', 'Report created'), ('REPORT_STATUS_CHANGED', 'Report status changed'), ('SIGHTING_CREATED', 'Sighting created'), ('SIGHTING_MARKED_USEFUL', 'Sighting marked useful'), ('SIGHTING_MARKED_FALSE', 'Sighting marked false')], max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=300)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_in_app_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to='reports.lostcatreport')),
                ('sighting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to='sightings.sighting')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_09c645_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_21a7ca_idx'), models.Index(fields=['event_type', '-created_at'], name='notificatio_event_t_382c4e_idx')],
            },
        ),
    ]
