/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#eeeeee',
        surface: '#f9f9f9',
        'on-primary': '#ffffff',
        'secondary-fixed': '#e5e2e1',
        'on-primary-fixed-variant': '#92001b',
        'surface-container-highest': '#e2e2e2',
        'on-primary-container': '#61000e',
        'primary-fixed': '#ffdad8',
        'inverse-primary': '#ffb3b0',
        'tertiary-fixed-dim': '#c8c6c6',
        primary: '#b52330',
        secondary: '#5f5e5e',
        'surface-variant': '#e2e2e2',
        'on-tertiary-fixed': '#1b1c1c',
        'tertiary-container': '#949393',
        'on-background': '#1a1c1c',
        'primary-fixed-dim': '#ffb3b0',
        'surface-tint': '#b52330',
        'primary-container': '#ff5a5f',
        outline: '#8e706f',
        'secondary-container': '#e2dfde',
        'surface-container-low': '#f3f3f3',
        'on-surface': '#1a1c1c',
        'inverse-surface': '#2f3131',
        'surface-dim': '#dadada',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#1c1b1b',
        'on-tertiary-container': '#2c2c2c',
        'secondary-fixed-dim': '#c8c6c5',
        'surface-container-high': '#e8e8e8',
        background: '#f9f9f9',
        'on-primary-fixed': '#410007',
        tertiary: '#5f5e5e',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#474746',
        'surface-bright': '#f9f9f9',
        'on-secondary-container': '#636262',
        'on-surface-variant': '#5a403f',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#e4e2e1',
        'on-tertiary-fixed-variant': '#474747',
        'inverse-on-surface': '#f0f1f1',
        'outline-variant': '#e2bebc',
        error: '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        sm: '12px',
        lg: '40px',
        base: '8px',
        'container-max': '1200px',
        'margin-mobile': '16px',
        md: '24px',
        xs: '4px',
        xl: '64px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
