"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=None):
    value = os.getenv(name)
    if not value:
        return default or []
    return [item.strip() for item in value.split(',') if item.strip()]


def env_int(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    return int(value)


def load_local_env(env_path):
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        name, value = line.split('=', 1)
        name = name.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]

        os.environ.setdefault(name, value)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_local_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-q76^mha&@(ovynxbrpx70f#8+u#p*ei&1t^5p%=5gqlfldokfc',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', ['localhost'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'api',
    'accounts',
    'reports',
    'sightings',
    'notifications',
    'posters',
    'points',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

AUTH_USER_MODEL = 'accounts.User'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ACCOUNT_VERIFICATION_RESEND_SECONDS = env_int('DJANGO_ACCOUNT_VERIFICATION_RESEND_SECONDS', 120)
EMAIL_BACKEND = os.getenv(
    'DJANGO_EMAIL_BACKEND',
    os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'),
)
DEFAULT_FROM_EMAIL = os.getenv(
    'DJANGO_DEFAULT_FROM_EMAIL',
    os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@catsos.local'),
)
EMAIL_HOST = os.getenv('DJANGO_EMAIL_HOST', os.getenv('EMAIL_HOST', 'localhost'))
EMAIL_PORT = env_int('DJANGO_EMAIL_PORT', env_int('EMAIL_PORT', 25))
EMAIL_HOST_USER = os.getenv('DJANGO_EMAIL_HOST_USER', os.getenv('EMAIL_HOST_USER', ''))
EMAIL_HOST_PASSWORD = os.getenv(
    'DJANGO_EMAIL_HOST_PASSWORD',
    os.getenv('EMAIL_HOST_PASSWORD', ''),
)
EMAIL_USE_TLS = env_bool('DJANGO_EMAIL_USE_TLS', env_bool('EMAIL_USE_TLS', False))
EMAIL_USE_SSL = env_bool('DJANGO_EMAIL_USE_SSL', env_bool('EMAIL_USE_SSL', False))
EMAIL_TIMEOUT = env_int('DJANGO_EMAIL_TIMEOUT', env_int('EMAIL_TIMEOUT', 10))
FRONTEND_URL = os.getenv(
    'DJANGO_FRONTEND_URL',
    os.getenv('FRONTEND_URL', 'http://localhost:5173'),
).rstrip('/')
PASSWORD_RESET_TIMEOUT = env_int(
    'DJANGO_PASSWORD_RESET_TIMEOUT',
    env_int('PASSWORD_RESET_TIMEOUT', 3600),
)
PASSWORD_RESET_EMAIL_RATE_LIMIT_PER_HOUR = env_int(
    'DJANGO_PASSWORD_RESET_EMAIL_RATE_LIMIT_PER_HOUR',
    5,
)
PASSWORD_RESET_IP_RATE_LIMIT_PER_HOUR = env_int(
    'DJANGO_PASSWORD_RESET_IP_RATE_LIMIT_PER_HOUR',
    10,
)
TOTP_ISSUER_NAME = os.getenv('DJANGO_TOTP_ISSUER_NAME', 'CatSOS')
TOTP_STEP_SECONDS = env_int('DJANGO_TOTP_STEP_SECONDS', 30)
TOTP_DIGITS = env_int('DJANGO_TOTP_DIGITS', 6)
TOTP_WINDOW = env_int('DJANGO_TOTP_WINDOW', 1)
GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID', '')
MICROSOFT_OAUTH_CLIENT_ID = os.getenv('MICROSOFT_OAUTH_CLIENT_ID', '')
MICROSOFT_JWKS_URL = os.getenv(
    'MICROSOFT_JWKS_URL',
    'https://login.microsoftonline.com/common/discovery/v2.0/keys',
)
SSO_HTTP_TIMEOUT_SECONDS = env_int('DJANGO_SSO_HTTP_TIMEOUT_SECONDS', 5)


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

PROFILE_PICTURE_MAX_SIZE_BYTES = env_int(
    'DJANGO_PROFILE_PICTURE_MAX_SIZE_BYTES',
    5 * 1024 * 1024,
)
REPORT_PHOTO_MAX_SIZE_BYTES = env_int(
    'DJANGO_REPORT_PHOTO_MAX_SIZE_BYTES',
    5 * 1024 * 1024,
)
SIGHTING_PHOTO_MAX_SIZE_BYTES = env_int(
    'DJANGO_SIGHTING_PHOTO_MAX_SIZE_BYTES',
    5 * 1024 * 1024,
)

CORS_ALLOWED_ORIGINS = env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    ['http://localhost:5173'],
)

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS', CORS_ALLOWED_ORIGINS)

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth_register': os.getenv('DJANGO_AUTH_REGISTER_RATE', '20/hour'),
        'auth_verify': os.getenv('DJANGO_AUTH_VERIFY_RATE', '30/minute'),
        'auth_resend': os.getenv('DJANGO_AUTH_RESEND_RATE', '10/hour'),
        'auth_change_email': os.getenv('DJANGO_AUTH_CHANGE_EMAIL_RATE', '10/hour'),
        'auth_login': os.getenv('DJANGO_AUTH_LOGIN_RATE', '20/minute'),
        'auth_token_refresh': os.getenv('DJANGO_AUTH_TOKEN_REFRESH_RATE', '60/minute'),
        'auth_sso_login': os.getenv('DJANGO_AUTH_SSO_LOGIN_RATE', '20/minute'),
        'auth_sso_link': os.getenv('DJANGO_AUTH_SSO_LINK_RATE', '20/minute'),
        'public_profile': os.getenv('DJANGO_PUBLIC_PROFILE_RATE', '120/minute'),
        'notification_read': os.getenv('DJANGO_NOTIFICATION_READ_RATE', '120/minute'),
        'points_read': os.getenv('DJANGO_POINTS_READ_RATE', '120/minute'),
        'lost_report_read': os.getenv('DJANGO_LOST_REPORT_READ_RATE', '120/minute'),
        'lost_report_write': os.getenv('DJANGO_LOST_REPORT_WRITE_RATE', '30/minute'),
        'sighting_write': os.getenv('DJANGO_SIGHTING_WRITE_RATE', '30/minute'),
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CatSOS API',
    'DESCRIPTION': 'Backend API for the CatSOS application.',
    'VERSION': '0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
