# Generated by Django 6.0.6 on 2026-07-06 20:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0006_alter_lostcatreporttimelineevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seen_at', models.DateTimeField()),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('confidence', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('USEFUL', 'Useful'), ('FALSE', 'False')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='reports.lostcatreport')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_sightings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-seen_at', '-created_at'),
                'indexes': [models.Index(fields=['report', '-seen_at'], name='sightings_s_report__8a7b60_idx'), models.Index(fields=['submitted_by', '-created_at'], name='sightings_s_submitt_35409e_idx'), models.Index(fields=['verification_status', '-created_at'], name='sightings_s_verific_b78a49_idx')],
            },
        ),
    ]
