# Generated by Django 6.0.6 on 2026-07-06 21:22

import django.db.models.deletion
import sightings.models
import sightings.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=sightings.models.sighting_photo_upload_to, validators=[sightings.validators.validate_sighting_photo_upload])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sightings.sighting')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sighting_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['sighting', 'created_at'], name='sightings_s_sightin_669b95_idx'), models.Index(fields=['uploaded_by', '-created_at'], name='sightings_s_uploade_51ef81_idx')],
            },
        ),
    ]
