# Generated by Django 6.0.6 on 2026-07-06 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0007_alter_lostcatreporttimelineevent_event_type'),
        ('sightings', '0002_sightingphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='verified_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='verified_sightings',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='sighting',
            index=models.Index(fields=['verified_by', '-verified_at'], name='sightings_s_verifie_b28277_idx'),
        ),
    ]
