# Generated by Django 6.0.6 on 2026-07-07 00:54

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_lostcatreporttimelineevent_event_type'),
        ('sightings', '0003_sighting_verified_at_sighting_verified_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerSearch',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'report',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='volunteer_searches',
                        to='reports.lostcatreport',
                    ),
                ),
                (
                    'volunteer',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='volunteer_searches',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'indexes': [
                    models.Index(
                        fields=['report', '-updated_at'],
                        name='sightings_v_report__08e2ea_idx',
                    ),
                    models.Index(
                        fields=['volunteer', '-updated_at'],
                        name='sightings_v_volunte_77a450_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('report', 'volunteer'),
                        name='unique_volunteer_search_per_report',
                    )
                ],
            },
        ),
    ]
