# Generated by Django 6.0.6 on 2026-07-07 11:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('SIGHTING_SUBMITTED', 'Sighting submitted'), ('SIGHTING_MARKED_USEFUL', 'Sighting marked useful'), ('VOLUNTEER_SEARCH_STARTED', 'Volunteer search started'), ('HELPFUL_REPORT_UPDATE', 'Helpful report update')], max_length=40)),
                ('points', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='points_poin_user_id_9c5c1b_idx'), models.Index(fields=['reason', '-created_at'], name='points_poin_reason_ad4ad6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('points__gte', 1)), name='point_transaction_points_positive')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('FIRST_HELP', 'First help'), ('NEIGHBOR_HELPER', 'Neighbor helper'), ('SEARCH_REGULAR', 'Search regular'), ('TRUSTED_HELPER', 'Trusted helper')], max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('awarded_at',),
                'indexes': [models.Index(fields=['user', 'awarded_at'], name='points_user_user_id_365e6d_idx'), models.Index(fields=['code', 'awarded_at'], name='points_user_code_1606b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'code'), name='unique_user_badge_code')],
            },
        ),
    ]
