# Generated by Django 6.0.6 on 2026-07-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='code',
            field=models.CharField(choices=[('FIRST_HELP', 'First help'), ('NEIGHBOR_HELPER', 'Neighbor helper'), ('SEARCH_REGULAR', 'Search regular'), ('TRUSTED_HELPER', 'Trusted helper'), ('TRUSTED_REPORTER', 'Trusted reporter')], max_length=40),
        ),
    ]
